# coding: utf-8

"""
    ECommerce Checkout Flow API

    Registration, Address Information, Delivery Options, Payment, Confirmation

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.cart_api import CartApi


class TestCartApi(unittest.TestCase):
    """ CartApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.cart_api.CartApi()

    def tearDown(self):
        pass

    def test_checkout_available_countries_get_using_get(self):
        """
        Test case for checkout_available_countries_get_using_get

        Get available billing and shipping countries
        """
        pass

    def test_checkout_checkout_id_available_payment_methods_get_using_get(self):
        """
        Test case for checkout_checkout_id_available_payment_methods_get_using_get

        Get available payment methods
        """
        pass

    def test_checkout_checkout_id_available_shipping_methods_get_using_get(self):
        """
        Test case for checkout_checkout_id_available_shipping_methods_get_using_get

        Get shipping info
        """
        pass

    def test_checkout_checkout_id_billing_address_put_using_put(self):
        """
        Test case for checkout_checkout_id_billing_address_put_using_put

        Update the billing address
        """
        pass

    def test_checkout_checkout_id_customer_attributes_put_using_put(self):
        """
        Test case for checkout_checkout_id_customer_attributes_put_using_put

        Set or update customer attributes
        """
        pass

    def test_checkout_checkout_id_get_using_get(self):
        """
        Test case for checkout_checkout_id_get_using_get

        Get an existing cart
        """
        pass

    def test_checkout_checkout_id_items_item_id_delete_using_delete(self):
        """
        Test case for checkout_checkout_id_items_item_id_delete_using_delete

        Delete an item from the shopping cart
        """
        pass

    def test_checkout_checkout_id_items_item_id_put_using_put(self):
        """
        Test case for checkout_checkout_id_items_item_id_put_using_put

        Update an existing item from the shopping cart
        """
        pass

    def test_checkout_checkout_id_pay_post_using_post(self):
        """
        Test case for checkout_checkout_id_pay_post_using_post

        Pay the cart total
        """
        pass

    def test_checkout_checkout_id_shipping_address_put_using_put(self):
        """
        Test case for checkout_checkout_id_shipping_address_put_using_put

        Update the shipping address
        """
        pass

    def test_checkout_checkout_id_shipping_method_put_using_put(self):
        """
        Test case for checkout_checkout_id_shipping_method_put_using_put

        Set or update the shipping method
        """
        pass

    def test_create_cart_using_post(self):
        """
        Test case for create_cart_using_post

        Create a possibly empty shopping cart
        """
        pass

    def test_create_item_using_post(self):
        """
        Test case for create_item_using_post

        Add a new item to the shopping cart
        """
        pass


if __name__ == '__main__':
    unittest.main()
