# coding: utf-8

"""
    ECommerce Checkout Flow API

    Registration, Address Information, Delivery Options, Payment, Confirmation

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Address(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, address1=None, address2=None, city=None, company=None, country=None, custom1=None, custom2=None, custom3=None, email=None, first_name=None, last_name=None, phone=None, state=None, tax_id=None, zip=None):
        """
        Address - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'address1': 'str',
            'address2': 'str',
            'city': 'str',
            'company': 'str',
            'country': 'str',
            'custom1': 'str',
            'custom2': 'str',
            'custom3': 'str',
            'email': 'str',
            'first_name': 'str',
            'last_name': 'str',
            'phone': 'str',
            'state': 'str',
            'tax_id': 'str',
            'zip': 'str'
        }

        self.attribute_map = {
            'address1': 'address1',
            'address2': 'address2',
            'city': 'city',
            'company': 'company',
            'country': 'country',
            'custom1': 'custom1',
            'custom2': 'custom2',
            'custom3': 'custom3',
            'email': 'email',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'phone': 'phone',
            'state': 'state',
            'tax_id': 'tax_id',
            'zip': 'zip'
        }

        self._address1 = address1
        self._address2 = address2
        self._city = city
        self._company = company
        self._country = country
        self._custom1 = custom1
        self._custom2 = custom2
        self._custom3 = custom3
        self._email = email
        self._first_name = first_name
        self._last_name = last_name
        self._phone = phone
        self._state = state
        self._tax_id = tax_id
        self._zip = zip


    @property
    def address1(self):
        """
        Gets the address1 of this Address.


        :return: The address1 of this Address.
        :rtype: str
        """
        return self._address1

    @address1.setter
    def address1(self, address1):
        """
        Sets the address1 of this Address.


        :param address1: The address1 of this Address.
        :type: str
        """

        self._address1 = address1

    @property
    def address2(self):
        """
        Gets the address2 of this Address.


        :return: The address2 of this Address.
        :rtype: str
        """
        return self._address2

    @address2.setter
    def address2(self, address2):
        """
        Sets the address2 of this Address.


        :param address2: The address2 of this Address.
        :type: str
        """

        self._address2 = address2

    @property
    def city(self):
        """
        Gets the city of this Address.


        :return: The city of this Address.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this Address.


        :param city: The city of this Address.
        :type: str
        """

        self._city = city

    @property
    def company(self):
        """
        Gets the company of this Address.


        :return: The company of this Address.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """
        Sets the company of this Address.


        :param company: The company of this Address.
        :type: str
        """

        self._company = company

    @property
    def country(self):
        """
        Gets the country of this Address.


        :return: The country of this Address.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this Address.


        :param country: The country of this Address.
        :type: str
        """

        self._country = country

    @property
    def custom1(self):
        """
        Gets the custom1 of this Address.


        :return: The custom1 of this Address.
        :rtype: str
        """
        return self._custom1

    @custom1.setter
    def custom1(self, custom1):
        """
        Sets the custom1 of this Address.


        :param custom1: The custom1 of this Address.
        :type: str
        """

        self._custom1 = custom1

    @property
    def custom2(self):
        """
        Gets the custom2 of this Address.


        :return: The custom2 of this Address.
        :rtype: str
        """
        return self._custom2

    @custom2.setter
    def custom2(self, custom2):
        """
        Sets the custom2 of this Address.


        :param custom2: The custom2 of this Address.
        :type: str
        """

        self._custom2 = custom2

    @property
    def custom3(self):
        """
        Gets the custom3 of this Address.


        :return: The custom3 of this Address.
        :rtype: str
        """
        return self._custom3

    @custom3.setter
    def custom3(self, custom3):
        """
        Sets the custom3 of this Address.


        :param custom3: The custom3 of this Address.
        :type: str
        """

        self._custom3 = custom3

    @property
    def email(self):
        """
        Gets the email of this Address.


        :return: The email of this Address.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this Address.


        :param email: The email of this Address.
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this Address.


        :return: The first_name of this Address.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this Address.


        :param first_name: The first_name of this Address.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this Address.


        :return: The last_name of this Address.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this Address.


        :param last_name: The last_name of this Address.
        :type: str
        """

        self._last_name = last_name

    @property
    def phone(self):
        """
        Gets the phone of this Address.


        :return: The phone of this Address.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """
        Sets the phone of this Address.


        :param phone: The phone of this Address.
        :type: str
        """

        self._phone = phone

    @property
    def state(self):
        """
        Gets the state of this Address.


        :return: The state of this Address.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this Address.


        :param state: The state of this Address.
        :type: str
        """

        self._state = state

    @property
    def tax_id(self):
        """
        Gets the tax_id of this Address.


        :return: The tax_id of this Address.
        :rtype: str
        """
        return self._tax_id

    @tax_id.setter
    def tax_id(self, tax_id):
        """
        Sets the tax_id of this Address.


        :param tax_id: The tax_id of this Address.
        :type: str
        """

        self._tax_id = tax_id

    @property
    def zip(self):
        """
        Gets the zip of this Address.


        :return: The zip of this Address.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """
        Sets the zip of this Address.


        :param zip: The zip of this Address.
        :type: str
        """

        self._zip = zip

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
